#!/bin/csh

pwd; users

source ../../../../set_wdmlibdir
set wdmlibdir = ../../../$wdmlibdir
set wdmlib1   = $wdmlibdir/wdmlib.a
set wdmlib2   = $wdmlibdir/adwdmlib.a
set wdmlib3   = $wdmlibdir/utillib.a

echo ""
date
echo "... compiling src"
f77 -mcmodel=medium -fbounds-check -c ../comidsdb.f
f77 -mcmodel=medium -fbounds-check -c ../streamtopologydb.f 
f77 -mcmodel=medium -fbounds-check -c ../landuse.f

f77 -mcmodel=medium -fbounds-check -c sum_eos.f
f77 -mcmodel=medium -fbounds-check -c main_sum_eos.f

echo "... linking objects"
f77 -o sum_eos.exe main_sum_eos.o sum_eos.o landuse.o streamtopologydb.o comidsdb.o ../../../lib/util_lib.a ../../../lib/dsn/dsn_utils.o $wdmlib1 $wdmlib2 $wdmlib3

echo "... cleaning up"
rm sum_eos.o

rm comidsdb.o
rm streamtopologydb.o

ls -altr *.exe

echo "... done compiling"
echo ""
