riv.seg <- 'RU5_6030_0001'

# Go to http://deq2.bse.vt.edu/d.dh/dh-search-watersheds, change "ftype" to "CBP 6.0 LRSegs",
# and paste the riv.seg into the Hydrocode -- click search and copy these LRSeg names into 
# these variables.
lriv.seg1 <- 'N51177_RU5_6030_0001'
lriv.seg2 <- 'N51179_RU5_6030_0001'
lriv.seg3 <- 'N51630_RU5_6030_0001'

# Specify run ID of scenario being analyzed as well as appropriate starting/ending dates for analysis
run.id <- '120'
start.date <- '1984-01-01'
end.date <- '2014-12-31'

# Change to location of the folder containing your cbp6 repository:
github_link <- "C:\\Users\\danie\\Documents\\HARP\\GitHub"

# Should all work automatically if github_link is correct
cbp6_link <- paste0(github_link, "/cbp6/code");
source(paste0(cbp6_link,"/cbp6_functions.R"))
source(paste(github_link,"auth.private", sep = "/")); #load rest username and password, contained in
source(paste(cbp6_link, "/fn_vahydro-1.0.R", sep = ''))
site <- "http://deq2.bse.vt.edu/d.dh"
token <- rest_token(site, token, rest_uname, rest_pw);

# Download data for the river segment's model run for future comparison:
dat.r <- vahydro_import_data_cfs(riv.seg = riv.seg, run.id = run.id, site = site,
                                 token = token, start.date = start.date, end.date = end.date)

# Downloads data for each land-river segment's run
dat.lr1 <- vahydro_import_lrseg_data_cfs(riv.seg = lriv.seg1, run.id = run.id, site = site,
                                         token = token, start.date = start.date, end.date = end.date)
dat.lr2 <- vahydro_import_lrseg_data_cfs(riv.seg = lriv.seg2, run.id = run.id, site = site,
                                         token = token, start.date = start.date, end.date = end.date)
dat.lr3 <- vahydro_import_lrseg_data_cfs(riv.seg = lriv.seg3, run.id = run.id, site = site,
                                         token = token, start.date = start.date, end.date = end.date)

# Compare the magnitude of the flows being generated by land-river segments to total flows
mean(dat.lr1$flow) + mean(dat.lr2$flow) + mean(dat.lr3$flow) # 36.5 cfs
mean(dat.r$flow) # 1763.4 cfs -- runoff from land-river segments makes up only a tiny part of
# the modeled flow for this river segment

# Let's compare the mean of the lr seg flows to those of the r seg flows pre- and post- 2005
# first, split up the data
library(lubridate)
dat.lr1.pre06 <- dat.lr1[year(dat.lr1$date) <= 2005,]
dat.lr1.06on <- dat.lr1[year(dat.lr1$date) > 2005,]
dat.lr2.pre06 <- dat.lr2[year(dat.lr2$date) <= 2005,]
dat.lr2.06on <- dat.lr2[year(dat.lr2$date) > 2005,]
dat.lr3.pre06 <- dat.lr3[year(dat.lr3$date) <= 2005,]
dat.lr3.06on <- dat.lr3[year(dat.lr3$date) > 2005,]
dat.r.pre06 <- dat.r[year(dat.r$date) <= 2005,]
dat.r.06on <- dat.r[year(dat.r$date) > 2005,]

# Now, lets compare
mean(dat.lr1.pre06$flow) + mean(dat.lr2.pre06$flow) + mean(dat.lr3.pre06$flow) # 37.36 cfs
mean(dat.lr1.06on$flow) + mean(dat.lr2.06on$flow) + mean(dat.lr3.06on$flow) # 34.56 cfs
# Hmmm... slightly decreased average flows from land-river segments after 2005 --
# the problem seems not to lie with the flows generated within this river segment.

mean(dat.r.pre06$flow) #1740.6 cfs
mean(dat.r.06on$flow) #1819.1 cfs
# This confirms what we already knew -- the river segment flows are significantly higher post-2005
# There is about an 80 cfs rise in average flow starting in 2006.

# Next, let's look into the local runoff inflows of this segment using a new function thrown
# into the CBP6 file.
local.runoff.inflows <- vahydro_import_local.runoff.inflows_cfs(riv.seg = riv.seg, run.id = run.id,
                                                                token = token, site = site, 
                                                                start.date = start.date,
                                                                end.date = end.date)
mean(local.runoff.inflows$flow.unit) # 0.941 cfs/sq.mi.

# Let's snag the drainage area from VA Hydro so we can turn multiply this into a true value
# instead of just a unit value
hydrocode = paste("vahydrosw_wshed_",riv.seg,sep="");
ftype = 'vahydro'; # nhd_huc8, nhd_huc10, vahydro
inputs <- list (
  hydrocode = hydrocode,
  bundle = 'watershed',
  ftype = 'vahydro'
)

#property dataframe returned
feature = FALSE;
odata <- getFeature(inputs, token, site, feature);
hydroid <- odata[1,"hydroid"];
fname <- as.character(odata[1,]$name );
print(paste("Retrieved hydroid",hydroid,"for", fname,riv.seg, sep=' '));

areainfo <- list(
  varkey = "wshed_drainage_area_sqmi",
  featureid = as.integer(as.character(hydroid)),
  entity_type = "dh_feature"
)

model.area <- getPropertyALT(areainfo, site, model.area, token)
area <- model.area$propvalue

# Multiplying the unit flow by this area:
mean(local.runoff.inflows$flow.unit) * area #1503.4 cfs 

# A basic water balance:
(mean(dat.r$flow)) - (mean(dat.lr1$flow) + mean(dat.lr2$flow) + mean(dat.lr3$flow)) - (mean(local.runoff.inflows$flow.unit) * area) #223.5 cfs
# Huh -- where is this 223.4083 cfs coming from if it is not generated from the land-river segments
# or coming from upstream rivers? I think this is an issue of me just not knowing enough about the 
# model -- Rob can probably explain this away.

# We'll also check pre-06 and 06-on average flows for the local.runoff.inflows
local.runoff.inflows.pre06 <- local.runoff.inflows[year(local.runoff.inflows$date)>=2005,]
local.runoff.inflows.06on <- local.runoff.inflows[year(local.runoff.inflows$date)>2005,]

mean(local.runoff.inflows.pre06$flow.unit) * area
mean(local.runoff.inflows.06on$flow.unit) * area 
# Hmmmm... the local runoff inflows are also slightly decreasing from '06 on, so this doesn't
# seem to be the problem either...

# Splitting the water balance up to pre- and post- 2006:
pre.unexplained <- (mean(dat.r.pre06$flow)) - (mean(dat.lr1.pre06$flow) + mean(dat.lr2.pre06$flow) + mean(dat.lr3.pre06$flow)) - (mean(local.runoff.inflows.pre06$flow.unit) * area)
pre.unexplained # 265.5 cfs

post.unexplained <- (mean(dat.r.06on$flow)) - (mean(dat.lr1.06on$flow) + mean(dat.lr2.06on$flow) + mean(dat.lr3.06on$flow)) - (mean(local.runoff.inflows.06on$flow.unit) * area)
post.unexplained # 362.9 cfs
# There is an increase in what I'm calling "unexplained water" solely because I'm not sure 
# where in the model it is coming from -- looking into this may be a next step?
# This pre- to post- Jan1. 2006 average difference in "unexplained water" is about 100 cfs -- greater than the difference
# in river segment surface runoff that we're seeing pre- to post- Jan1.2006.