#' Baseflow Metric Function 
#' @description Calculates 65 different hydrologic metrics from the given dataframe - must be trimmed to water year 
#' @param data a dataframe with hydrologic data 
#' @return A data frame with 65 different hydrologic metrics
#' @export metrics_calc_all

# Creating Data Frame with calculated metrics 
metrics_calc_all <- function(data) {
  overall.mean <- overall_mean_flow(data)
  jan.low.flow <- monthly_min(data, num.month = 1)
  feb.low.flow <- monthly_min(data, num.month = 2)
  mar.low.flow <- monthly_min(data, num.month = 3)
  apr.low.flow <- monthly_min(data, num.month = 4)
  may.low.flow <- monthly_min(data, num.month = 5)
  jun.low.flow <- monthly_min(data, num.month = 6)
  jul.low.flow <- monthly_min(data, num.month = 7)
  aug.low.flow <- monthly_min(data, num.month = 8)
  sep.low.flow <- monthly_min(data, num.month = 9)
  oct.low.flow <- monthly_min(data, num.month = 10)
  nov.low.flow <- monthly_min(data, num.month = 11)
  dec.low.flow <- monthly_min(data, num.month = 12)
  jan.mean.flow <- monthly_mean(data, num.month = 1)
  feb.mean.flow <- monthly_mean(data, num.month = 2)
  mar.mean.flow <- monthly_mean(data, num.month = 3)
  apr.mean.flow <- monthly_mean(data, num.month = 4)
  may.mean.flow <- monthly_mean(data, num.month = 5)
  jun.mean.flow <- monthly_mean(data, num.month = 6)
  jul.mean.flow <- monthly_mean(data, num.month = 7)
  aug.mean.flow <- monthly_mean(data, num.month = 8)
  sep.mean.flow <- monthly_mean(data, num.month = 9)
  oct.mean.flow <- monthly_mean(data, num.month = 10)
  nov.mean.flow <- monthly_mean(data, num.month = 11)
  dec.mean.flow <- monthly_mean(data, num.month = 12)
  jan.high.flow <- monthly_max(data, num.month = 1)
  feb.high.flow <- monthly_max(data, num.month = 2)
  mar.high.flow <- monthly_max(data, num.month = 3)
  apr.high.flow <- monthly_max(data, num.month = 4)
  may.high.flow <- monthly_max(data, num.month = 5)
  jun.high.flow <- monthly_max(data, num.month = 6)
  jul.high.flow <- monthly_max(data, num.month = 7)
  aug.high.flow <- monthly_max(data, num.month = 8)
  sep.high.flow <- monthly_max(data, num.month = 9)
  oct.high.flow <- monthly_max(data, num.month = 10)
  nov.high.flow <- monthly_max(data, num.month = 11)
  dec.high.flow <- monthly_max(data, num.month = 12)
  one.day.min <- num_day_min(data, num.day = 1, min_or_med = "min")
  three.day.min <- num_day_min(data, num.day = 3, min_or_med = "min")
  seven.day.min <- num_day_min(data, num.day = 7, min_or_med = "min")
  thirty.day.min <- num_day_min(data, num.day = 30, min_or_med = "min")
  ninety.day.min <- num_day_min(data, num.day = 90, min_or_med = "min")
  one.day.med.min <- num_day_min(data, num.day = 1, min_or_med = "med")
  three.day.med.min <- num_day_min(data, num.day = 3, min_or_med = "med")
  seven.day.med.min <- num_day_min(data, num.day = 7, min_or_med = "med")
  thirty.day.med.min <- num_day_min(data, num.day = 30, min_or_med = "med")
  ninety.day.med.min <- num_day_min(data, num.day = 90, min_or_med = "med")
  one.day.max <- num_day_max(data, num.day = 1, max_or_med = "max")
  three.day.max <- num_day_max(data, num.day = 3, max_or_med = "max")
  seven.day.max <- num_day_max(data, num.day = 7, max_or_med = "max")
  thirty.day.max <- num_day_max(data, num.day = 30, max_or_med = "max")
  ninety.day.max <- num_day_max(data, num.day = 90, max_or_med = "max")
  one.day.med.max <- num_day_max(data, num.day = 1, max_or_med = "med")
  three.day.med.max <- num_day_max(data, num.day = 3, max_or_med = "med")
  seven.day.med.max <- num_day_max(data, num.day = 7, max_or_med = "med")
  thirty.day.med.max <- num_day_max(data, num.day = 30, max_or_med = "med")
  ninety.day.med.max <- num_day_max(data, num.day = 90, max_or_med = "med")
  lowest.yearly.mean <- low_yearly_mean(data)
  sevenQ.ten <- seven_q_ten(data)
  drought.record <- drought_of_record(data)
  sept.10.percent <- sept_10_flow(data)
  flow.exceedance.1 <- flow_exceedance(data, prob = 0.01)
  flow.exceedance.5 <- flow_exceedance(data, prob = 0.05)
  flow.exceedance.50 <- flow_exceedance(data, prob = 0.5)
  flow.exceedance.95 <- flow_exceedance(data, prob = 0.95)
  flow.exceedance.99 <- flow_exceedance(data, prob = 0.99)
  avg.baseflow <- average_baseflow(data)
  
  all_metrics <- data.frame(overall.mean, jan.low.flow, feb.low.flow, mar.low.flow, apr.low.flow, may.low.flow,jun.low.flow, jul.low.flow, aug.low.flow, sep.low.flow, oct.low.flow, nov.low.flow, dec.low.flow, jan.mean.flow, feb.mean.flow, mar.mean.flow, apr.mean.flow, may.mean.flow, jun.mean.flow, jul.mean.flow, aug.mean.flow, sep.mean.flow, oct.mean.flow, nov.mean.flow, dec.mean.flow, jan.high.flow, feb.high.flow, mar.high.flow, apr.high.flow, may.high.flow, jun.high.flow, jul.high.flow, aug.high.flow, sep.high.flow, oct.high.flow, nov.high.flow, dec.high.flow, one.day.min, three.day.min, seven.day.min, thirty.day.min, ninety.day.min, one.day.med.min, three.day.med.min, seven.day.med.min, thirty.day.med.min, ninety.day.med.min, one.day.max, three.day.max, seven.day.max, thirty.day.max, ninety.day.max, one.day.med.max, three.day.med.max, seven.day.med.max, thirty.day.med.max, ninety.day.med.max, lowest.yearly.mean, sevenQ.ten, drought.record, sept.10.percent, flow.exceedance.1, flow.exceedance.5, flow.exceedance.50, flow.exceedance.95, flow.exceedance.99, avg.baseflow)
  rownames(all_metrics) <- 'analysis'
  return(all_metrics)
}