library(knitr)

tab.iqr.by.lrseg.land.use = function(tmp.data) {
  aop.names <- grep('aop', colnames(tmp.data), value = TRUE)
  aop.cols <- which(colnames(tmp.data) %in% aop.names)
  aop.data <- as.numeric(as.matrix(tmp.data[,aop.cols]))
  aop.75pct <- signif(as.numeric(quantile(aop.data, 0.75)), 3)
  aop.25pct <- signif(as.numeric(quantile(aop.data, 0.25)), 3)
  aop.iqr <- signif(aop.75pct - aop.25pct, 3)
  aop.tabler <- paste0(aop.iqr, ' [', aop.25pct, ', ', aop.75pct, ']')
  
  ccn.names <- grep('ccn', colnames(tmp.data), value = TRUE)
  ccn.cols <- which(colnames(tmp.data) %in% ccn.names)
  ccn.data <- as.numeric(as.matrix(tmp.data[,ccn.cols]))
  ccn.75pct <- signif(as.numeric(quantile(ccn.data, 0.75)), 3)
  ccn.25pct <- signif(as.numeric(quantile(ccn.data, 0.25)), 3)
  ccn.iqr <- signif(ccn.75pct - ccn.25pct, 3)
  ccn.tabler <- paste0(ccn.iqr, ' [', ccn.25pct, ', ', ccn.75pct, ']')
  
  cmo.names <- grep('cmo', colnames(tmp.data), value = TRUE)
  cmo.cols <- which(colnames(tmp.data) %in% cmo.names)
  cmo.data <- as.numeric(as.matrix(tmp.data[,cmo.cols]))
  cmo.75pct <- signif(as.numeric(quantile(cmo.data, 0.75)), 3)
  cmo.25pct <- signif(as.numeric(quantile(cmo.data, 0.25)), 3)
  cmo.iqr <- signif(cmo.75pct - cmo.25pct, 3)
  cmo.tabler <- paste0(cmo.iqr, ' [', cmo.25pct, ', ', cmo.75pct, ']')
  
  dbl.names <- grep('dbl', colnames(tmp.data), value = TRUE)
  dbl.cols <- which(colnames(tmp.data) %in% dbl.names)
  dbl.data <- as.numeric(as.matrix(tmp.data[,dbl.cols]))
  dbl.75pct <- signif(as.numeric(quantile(dbl.data, 0.75)), 3)
  dbl.25pct <- signif(as.numeric(quantile(dbl.data, 0.25)), 3)
  dbl.iqr <- signif(dbl.75pct - dbl.25pct, 3)
  dbl.tabler <- paste0(dbl.iqr, ' [', dbl.25pct, ', ', dbl.75pct, ']')
  
  fsp.names <- grep('fsp', colnames(tmp.data), value = TRUE)
  fsp.cols <- which(colnames(tmp.data) %in% fsp.names)
  fsp.data <- as.numeric(as.matrix(tmp.data[,fsp.cols]))
  fsp.75pct <- signif(as.numeric(quantile(fsp.data, 0.75)), 3)
  fsp.25pct <- signif(as.numeric(quantile(fsp.data, 0.25)), 3)
  fsp.iqr <- signif(fsp.75pct - fsp.25pct, 3)
  fsp.tabler <- paste0(fsp.iqr, ' [', fsp.25pct, ', ', fsp.75pct, ']')
  
  hfr.names <- grep('hfr', colnames(tmp.data), value = TRUE)
  hfr.cols <- which(colnames(tmp.data) %in% hfr.names)
  hfr.data <- as.numeric(as.matrix(tmp.data[,hfr.cols]))
  hfr.75pct <- signif(as.numeric(quantile(hfr.data, 0.75)), 3)
  hfr.25pct <- signif(as.numeric(quantile(hfr.data, 0.25)), 3)
  hfr.iqr <- signif(hfr.75pct - hfr.25pct, 3)
  hfr.tabler <- paste0(hfr.iqr, ' [', hfr.25pct, ', ', hfr.75pct, ']')
  
  mci.names <- grep('mci', colnames(tmp.data), value = TRUE)
  mci.cols <- which(colnames(tmp.data) %in% mci.names)
  mci.data <- as.numeric(as.matrix(tmp.data[,mci.cols]))
  mci.75pct <- signif(as.numeric(quantile(mci.data, 0.75)), 3)
  mci.25pct <- signif(as.numeric(quantile(mci.data, 0.25)), 3)
  mci.iqr <- signif(mci.75pct - mci.25pct, 3)
  mci.tabler <- paste0(mci.iqr, ' [', mci.25pct, ', ', mci.75pct, ']')
  
  mnr.names <- grep('mnr', colnames(tmp.data), value = TRUE)
  mnr.cols <- which(colnames(tmp.data) %in% mnr.names)
  mnr.data <- as.numeric(as.matrix(tmp.data[,mnr.cols]))
  mnr.75pct <- signif(as.numeric(quantile(mnr.data, 0.75)), 3)
  mnr.25pct <- signif(as.numeric(quantile(mnr.data, 0.25)), 3)
  mnr.iqr <- signif(mnr.75pct - mnr.25pct, 3)
  mnr.tabler <- paste0(mnr.iqr, ' [', mnr.25pct, ', ', mnr.75pct, ']')
  
  nci.names <- grep('nci', colnames(tmp.data), value = TRUE)
  nci.cols <- which(colnames(tmp.data) %in% nci.names)
  nci.data <- as.numeric(as.matrix(tmp.data[,nci.cols]))
  nci.75pct <- signif(as.numeric(quantile(nci.data, 0.75)), 3)
  nci.25pct <- signif(as.numeric(quantile(nci.data, 0.25)), 3)
  nci.iqr <- signif(nci.75pct - nci.25pct, 3)
  nci.tabler <- paste0(nci.iqr, ' [', nci.25pct, ', ', nci.75pct, ']')
  
  ntg.names <- grep('ntg', colnames(tmp.data), value = TRUE)
  ntg.cols <- which(colnames(tmp.data) %in% ntg.names)
  ntg.data <- as.numeric(as.matrix(tmp.data[,ntg.cols]))
  ntg.75pct <- signif(as.numeric(quantile(ntg.data, 0.75)), 3)
  ntg.25pct <- signif(as.numeric(quantile(ntg.data, 0.25)), 3)
  ntg.iqr <- signif(ntg.75pct - ntg.25pct, 3)
  ntg.tabler <- paste0(ntg.iqr, ' [', ntg.25pct, ', ', ntg.75pct, ']')
  
  osp.names <- grep('osp', colnames(tmp.data), value = TRUE)
  osp.cols <- which(colnames(tmp.data) %in% osp.names)
  osp.data <- as.numeric(as.matrix(tmp.data[,osp.cols]))
  osp.75pct <- signif(as.numeric(quantile(osp.data, 0.75)), 3)
  osp.25pct <- signif(as.numeric(quantile(osp.data, 0.25)), 3)
  osp.iqr <- signif(osp.75pct - osp.25pct, 3)
  osp.tabler <- paste0(osp.iqr, ' [', osp.25pct, ', ', osp.75pct, ']')
  
  scl.names <- grep('scl', colnames(tmp.data), value = TRUE)
  scl.cols <- which(colnames(tmp.data) %in% scl.names)
  scl.data <- as.numeric(as.matrix(tmp.data[,scl.cols]))
  scl.75pct <- signif(as.numeric(quantile(scl.data, 0.75)), 3)
  scl.25pct <- signif(as.numeric(quantile(scl.data, 0.25)), 3)
  scl.iqr <- signif(scl.75pct - scl.25pct, 3)
  scl.tabler <- paste0(scl.iqr, ' [', scl.25pct, ', ', scl.75pct, ']')
  
  som.names <- grep('som', colnames(tmp.data), value = TRUE)
  som.cols <- which(colnames(tmp.data) %in% som.names)
  som.data <- as.numeric(as.matrix(tmp.data[,som.cols]))
  som.75pct <- signif(as.numeric(quantile(som.data, 0.75)), 3)
  som.25pct <- signif(as.numeric(quantile(som.data, 0.25)), 3)
  som.iqr <- signif(som.75pct - som.25pct, 3)
  som.tabler <- paste0(som.iqr, ' [', som.25pct, ', ', som.75pct, ']')
  
  stf.names <- grep('stf', colnames(tmp.data), value = TRUE)
  stf.cols <- which(colnames(tmp.data) %in% stf.names)
  stf.data <- as.numeric(as.matrix(tmp.data[,stf.cols]))
  stf.75pct <- signif(as.numeric(quantile(stf.data, 0.75)), 3)
  stf.25pct <- signif(as.numeric(quantile(stf.data, 0.25)), 3)
  stf.iqr <- signif(stf.75pct - stf.25pct, 3)
  stf.tabler <- paste0(stf.iqr, ' [', stf.25pct, ', ', stf.75pct, ']')
  
  wto.names <- grep('wto', colnames(tmp.data), value = TRUE)
  wto.cols <- which(colnames(tmp.data) %in% wto.names)
  wto.data <- as.numeric(as.matrix(tmp.data[,wto.cols]))
  wto.75pct <- signif(as.numeric(quantile(wto.data, 0.75)), 3)
  wto.25pct <- signif(as.numeric(quantile(wto.data, 0.25)), 3)
  wto.iqr <- signif(wto.75pct - wto.25pct, 3)
  wto.tabler <- paste0(wto.iqr, ' [', wto.25pct, ', ', wto.75pct, ']')
  
  cch.names <- grep('cch', colnames(tmp.data), value = TRUE)
  cch.cols <- which(colnames(tmp.data) %in% cch.names)
  cch.data <- as.numeric(as.matrix(tmp.data[,cch.cols]))
  cch.75pct <- signif(as.numeric(quantile(cch.data, 0.75)), 3)
  cch.25pct <- signif(as.numeric(quantile(cch.data, 0.25)), 3)
  cch.iqr <- signif(cch.75pct - cch.25pct, 3)
  cch.tabler <- paste0(cch.iqr, ' [', cch.25pct, ', ', cch.75pct, ']')
  
  cfr.names <- grep('cfr', colnames(tmp.data), value = TRUE)
  cfr.cols <- which(colnames(tmp.data) %in% cfr.names)
  cfr.data <- as.numeric(as.matrix(tmp.data[,cfr.cols]))
  cfr.75pct <- signif(as.numeric(quantile(cfr.data, 0.75)), 3)
  cfr.25pct <- signif(as.numeric(quantile(cfr.data, 0.25)), 3)
  cfr.iqr <- signif(cfr.75pct - cfr.25pct, 3)
  cfr.tabler <- paste0(cfr.iqr, ' [', cfr.25pct, ', ', cfr.75pct, ']')
  
  cnr.names <- grep('cnr', colnames(tmp.data), value = TRUE)
  cnr.cols <- which(colnames(tmp.data) %in% cnr.names)
  cnr.data <- as.numeric(as.matrix(tmp.data[,cnr.cols]))
  cnr.75pct <- signif(as.numeric(quantile(cnr.data, 0.75)), 3)
  cnr.25pct <- signif(as.numeric(quantile(cnr.data, 0.25)), 3)
  cnr.iqr <- signif(cnr.75pct - cnr.25pct, 3)
  cnr.tabler <- paste0(cnr.iqr, ' [', cnr.25pct, ', ', cnr.75pct, ']')
  
  fnp.names <- grep('fnp', colnames(tmp.data), value = TRUE)
  fnp.cols <- which(colnames(tmp.data) %in% fnp.names)
  fnp.data <- as.numeric(as.matrix(tmp.data[,fnp.cols]))
  fnp.75pct <- signif(as.numeric(quantile(fnp.data, 0.75)), 3)
  fnp.25pct <- signif(as.numeric(quantile(fnp.data, 0.25)), 3)
  fnp.iqr <- signif(fnp.75pct - fnp.25pct, 3)
  fnp.tabler <- paste0(fnp.iqr, ' [', fnp.25pct, ', ', fnp.75pct, ']')
  
  gom.names <- grep('gom', colnames(tmp.data), value = TRUE)
  gom.cols <- which(colnames(tmp.data) %in% gom.names)
  gom.data <- as.numeric(as.matrix(tmp.data[,gom.cols]))
  gom.75pct <- signif(as.numeric(quantile(gom.data, 0.75)), 3)
  gom.25pct <- signif(as.numeric(quantile(gom.data, 0.25)), 3)
  gom.iqr <- signif(gom.75pct - gom.25pct, 3)
  gom.tabler <- paste0(gom.iqr, ' [', gom.25pct, ', ', gom.75pct, ']')
  
  lhy.names <- grep('lhy', colnames(tmp.data), value = TRUE)
  lhy.cols <- which(colnames(tmp.data) %in% lhy.names)
  lhy.data <- as.numeric(as.matrix(tmp.data[,lhy.cols]))
  lhy.75pct <- signif(as.numeric(quantile(lhy.data, 0.75)), 3)
  lhy.25pct <- signif(as.numeric(quantile(lhy.data, 0.25)), 3)
  lhy.iqr <- signif(lhy.75pct - lhy.25pct, 3)
  lhy.tabler <- paste0(lhy.iqr, ' [', lhy.25pct, ', ', lhy.75pct, ']')
  
  mcn.names <- grep('mcn', colnames(tmp.data), value = TRUE)
  mcn.cols <- which(colnames(tmp.data) %in% mcn.names)
  mcn.data <- as.numeric(as.matrix(tmp.data[,mcn.cols]))
  mcn.75pct <- signif(as.numeric(quantile(mcn.data, 0.75)), 3)
  mcn.25pct <- signif(as.numeric(quantile(mcn.data, 0.25)), 3)
  mcn.iqr <- signif(mcn.75pct - mcn.25pct, 3)
  mcn.tabler <- paste0(mcn.iqr, ' [', mcn.25pct, ', ', mcn.75pct, ']')
  
  mtg.names <- grep('mtg', colnames(tmp.data), value = TRUE)
  mtg.cols <- which(colnames(tmp.data) %in% mtg.names)
  mtg.data <- as.numeric(as.matrix(tmp.data[,mtg.cols]))
  mtg.75pct <- signif(as.numeric(quantile(mtg.data, 0.75)), 3)
  mtg.25pct <- signif(as.numeric(quantile(mtg.data, 0.25)), 3)
  mtg.iqr <- signif(mtg.75pct - mtg.25pct, 3)
  mtg.tabler <- paste0(mtg.iqr, ' [', mtg.25pct, ', ', mtg.75pct, ']')
  
  nir.names <- grep('nir', colnames(tmp.data), value = TRUE)
  nir.cols <- which(colnames(tmp.data) %in% nir.names)
  nir.data <- as.numeric(as.matrix(tmp.data[,nir.cols]))
  nir.75pct <- signif(as.numeric(quantile(nir.data, 0.75)), 3)
  nir.25pct <- signif(as.numeric(quantile(nir.data, 0.25)), 3)
  nir.iqr <- signif(nir.75pct - nir.25pct, 3)
  nir.tabler <- paste0(nir.iqr, ' [', nir.25pct, ', ', nir.75pct, ']')
  
  oac.names <- grep('oac', colnames(tmp.data), value = TRUE)
  oac.cols <- which(colnames(tmp.data) %in% oac.names)
  oac.data <- as.numeric(as.matrix(tmp.data[,oac.cols]))
  oac.75pct <- signif(as.numeric(quantile(oac.data, 0.75)), 3)
  oac.25pct <- signif(as.numeric(quantile(oac.data, 0.25)), 3)
  oac.iqr <- signif(oac.75pct - oac.25pct, 3)
  oac.tabler <- paste0(oac.iqr, ' [', oac.25pct, ', ', oac.75pct, ']')
  
  pas.names <- grep('pas', colnames(tmp.data), value = TRUE)
  pas.cols <- which(colnames(tmp.data) %in% pas.names)
  pas.data <- as.numeric(as.matrix(tmp.data[,pas.cols]))
  pas.75pct <- signif(as.numeric(quantile(pas.data, 0.75)), 3)
  pas.25pct <- signif(as.numeric(quantile(pas.data, 0.25)), 3)
  pas.iqr <- signif(pas.75pct - pas.25pct, 3)
  pas.tabler <- paste0(pas.iqr, ' [', pas.25pct, ', ', pas.75pct, ']')
  
  sgg.names <- grep('sgg', colnames(tmp.data), value = TRUE)
  sgg.cols <- which(colnames(tmp.data) %in% sgg.names)
  sgg.data <- as.numeric(as.matrix(tmp.data[,sgg.cols]))
  sgg.75pct <- signif(as.numeric(quantile(sgg.data, 0.75)), 3)
  sgg.25pct <- signif(as.numeric(quantile(sgg.data, 0.25)), 3)
  sgg.iqr <- signif(sgg.75pct - sgg.25pct, 3)
  sgg.tabler <- paste0(sgg.iqr, ' [', sgg.25pct, ', ', sgg.75pct, ']')
  
  soy.names <- grep('soy', colnames(tmp.data), value = TRUE)
  soy.cols <- which(colnames(tmp.data) %in% soy.names)
  soy.data <- as.numeric(as.matrix(tmp.data[,soy.cols]))
  soy.75pct <- signif(as.numeric(quantile(soy.data, 0.75)), 3)
  soy.25pct <- signif(as.numeric(quantile(soy.data, 0.25)), 3)
  soy.iqr <- signif(soy.75pct - soy.25pct, 3)
  soy.tabler <- paste0(soy.iqr, ' [', soy.25pct, ', ', soy.75pct, ']')
  
  swm.names <- grep('swm', colnames(tmp.data), value = TRUE)
  swm.cols <- which(colnames(tmp.data) %in% swm.names)
  swm.data <- as.numeric(as.matrix(tmp.data[,swm.cols]))
  swm.75pct <- signif(as.numeric(quantile(swm.data, 0.75)), 3)
  swm.25pct <- signif(as.numeric(quantile(swm.data, 0.25)), 3)
  swm.iqr <- signif(swm.75pct - swm.25pct, 3)
  swm.tabler <- paste0(swm.iqr, ' [', swm.25pct, ', ', swm.75pct, ']')
  
  cci.names <- grep('cci', colnames(tmp.data), value = TRUE)
  cci.cols <- which(colnames(tmp.data) %in% cci.names)
  cci.data <- as.numeric(as.matrix(tmp.data[,cci.cols]))
  cci.75pct <- signif(as.numeric(quantile(cci.data, 0.75)), 3)
  cci.25pct <- signif(as.numeric(quantile(cci.data, 0.25)), 3)
  cci.iqr <- signif(cci.75pct - cci.25pct, 3)
  cci.tabler <- paste0(cci.iqr, ' [', cci.25pct, ', ', cci.75pct, ']')
  
  cir.names <- grep('cir', colnames(tmp.data), value = TRUE)
  cir.cols <- which(colnames(tmp.data) %in% cir.names)
  cir.data <- as.numeric(as.matrix(tmp.data[,cir.cols]))
  cir.75pct <- signif(as.numeric(quantile(cir.data, 0.75)), 3)
  cir.25pct <- signif(as.numeric(quantile(cir.data, 0.25)), 3)
  cir.iqr <- signif(cir.75pct - cir.25pct, 3)
  cir.tabler <- paste0(cir.iqr, ' [', cir.25pct, ', ', cir.75pct, ']')
  
  ctg.names <- grep('ctg', colnames(tmp.data), value = TRUE)
  ctg.cols <- which(colnames(tmp.data) %in% ctg.names)
  ctg.data <- as.numeric(as.matrix(tmp.data[,ctg.cols]))
  ctg.75pct <- signif(as.numeric(quantile(ctg.data, 0.75)), 3)
  ctg.25pct <- signif(as.numeric(quantile(ctg.data, 0.25)), 3)
  ctg.iqr <- signif(ctg.75pct - ctg.25pct, 3)
  ctg.tabler <- paste0(ctg.iqr, ' [', ctg.25pct, ', ', ctg.75pct, ']')
  
  for.names <- grep('for', colnames(tmp.data), value = TRUE)
  for.cols <- which(colnames(tmp.data) %in% for.names)
  for.data <- as.numeric(as.matrix(tmp.data[,for.cols]))
  for.75pct <- signif(as.numeric(quantile(for.data, 0.75)), 3)
  for.25pct <- signif(as.numeric(quantile(for.data, 0.25)), 3)
  for.iqr <- signif(for.75pct - for.25pct, 3)
  for.tabler <- paste0(for.iqr, ' [', for.25pct, ', ', for.75pct, ']')
  
  gwm.names <- grep('gwm', colnames(tmp.data), value = TRUE)
  gwm.cols <- which(colnames(tmp.data) %in% gwm.names)
  gwm.data <- as.numeric(as.matrix(tmp.data[,gwm.cols]))
  gwm.75pct <- signif(as.numeric(quantile(gwm.data, 0.75)), 3)
  gwm.25pct <- signif(as.numeric(quantile(gwm.data, 0.25)), 3)
  gwm.iqr <- signif(gwm.75pct - gwm.25pct, 3)
  gwm.tabler <- paste0(gwm.iqr, ' [', gwm.25pct, ', ', gwm.75pct, ']')
  
  mch.names <- grep('mch', colnames(tmp.data), value = TRUE)
  mch.cols <- which(colnames(tmp.data) %in% mch.names)
  mch.data <- as.numeric(as.matrix(tmp.data[,mch.cols]))
  mch.75pct <- signif(as.numeric(quantile(mch.data, 0.75)), 3)
  mch.25pct <- signif(as.numeric(quantile(mch.data, 0.25)), 3)
  mch.iqr <- signif(mch.75pct - mch.25pct, 3)
  mch.tabler <- paste0(mch.iqr, ' [', mch.25pct, ', ', mch.75pct, ']')
  
  mir.names <- grep('mir', colnames(tmp.data), value = TRUE)
  mir.cols <- which(colnames(tmp.data) %in% mir.names)
  mir.data <- as.numeric(as.matrix(tmp.data[,mir.cols]))
  mir.75pct <- signif(as.numeric(quantile(mir.data, 0.75)), 3)
  mir.25pct <- signif(as.numeric(quantile(mir.data, 0.25)), 3)
  mir.iqr <- signif(mir.75pct - mir.25pct, 3)
  mir.tabler <- paste0(mir.iqr, ' [', mir.25pct, ', ', mir.75pct, ']')
  
  nch.names <- grep('nch', colnames(tmp.data), value = TRUE)
  nch.cols <- which(colnames(tmp.data) %in% nch.names)
  nch.data <- as.numeric(as.matrix(tmp.data[,nch.cols]))
  nch.75pct <- signif(as.numeric(quantile(nch.data, 0.75)), 3)
  nch.25pct <- signif(as.numeric(quantile(nch.data, 0.25)), 3)
  nch.iqr <- signif(nch.75pct - nch.25pct, 3)
  nch.tabler <- paste0(nch.iqr, ' [', nch.25pct, ', ', nch.75pct, ']')
  
  nnr.names <- grep('nnr', colnames(tmp.data), value = TRUE)
  nnr.cols <- which(colnames(tmp.data) %in% nnr.names)
  nnr.data <- as.numeric(as.matrix(tmp.data[,nnr.cols]))
  nnr.75pct <- signif(as.numeric(quantile(nnr.data, 0.75)), 3)
  nnr.25pct <- signif(as.numeric(quantile(nnr.data, 0.25)), 3)
  nnr.iqr <- signif(nnr.75pct - nnr.25pct, 3)
  nnr.tabler <- paste0(nnr.iqr, ' [', nnr.25pct, ', ', nnr.75pct, ']')
  
  ohy.names <- grep('ohy', colnames(tmp.data), value = TRUE)
  ohy.cols <- which(colnames(tmp.data) %in% ohy.names)
  ohy.data <- as.numeric(as.matrix(tmp.data[,ohy.cols]))
  ohy.75pct <- signif(as.numeric(quantile(ohy.data, 0.75)), 3)
  ohy.25pct <- signif(as.numeric(quantile(ohy.data, 0.25)), 3)
  ohy.iqr <- signif(ohy.75pct - ohy.25pct, 3)
  ohy.tabler <- paste0(ohy.iqr, ' [', ohy.25pct, ', ', ohy.75pct, ']')
  
  sch.names <- grep('sch', colnames(tmp.data), value = TRUE)
  sch.cols <- which(colnames(tmp.data) %in% sch.names)
  sch.data <- as.numeric(as.matrix(tmp.data[,sch.cols]))
  sch.75pct <- signif(as.numeric(quantile(sch.data, 0.75)), 3)
  sch.25pct <- signif(as.numeric(quantile(sch.data, 0.25)), 3)
  sch.iqr <- signif(sch.75pct - sch.25pct, 3)
  sch.tabler <- paste0(sch.iqr, ' [', sch.25pct, ', ', sch.75pct, ']')
  
  sho.names <- grep('sho', colnames(tmp.data), value = TRUE)
  sho.cols <- which(colnames(tmp.data) %in% sho.names)
  sho.data <- as.numeric(as.matrix(tmp.data[,sho.cols]))
  sho.75pct <- signif(as.numeric(quantile(sho.data, 0.75)), 3)
  sho.25pct <- signif(as.numeric(quantile(sho.data, 0.25)), 3)
  sho.iqr <- signif(sho.75pct - sho.25pct, 3)
  sho.tabler <- paste0(sho.iqr, ' [', sho.25pct, ', ', sho.75pct, ']')
  
  stb.names <- grep('stb', colnames(tmp.data), value = TRUE)
  stb.cols <- which(colnames(tmp.data) %in% stb.names)
  stb.data <- as.numeric(as.matrix(tmp.data[,stb.cols]))
  stb.75pct <- signif(as.numeric(quantile(stb.data, 0.75)), 3)
  stb.25pct <- signif(as.numeric(quantile(stb.data, 0.25)), 3)
  stb.iqr <- signif(stb.75pct - stb.25pct, 3)
  stb.tabler <- paste0(stb.iqr, ' [', stb.25pct, ', ', stb.75pct, ']')
  
  wfp.names <- grep('wfp', colnames(tmp.data), value = TRUE)
  wfp.cols <- which(colnames(tmp.data) %in% wfp.names)
  wfp.data <- as.numeric(as.matrix(tmp.data[,wfp.cols]))
  wfp.75pct <- signif(as.numeric(quantile(wfp.data, 0.75)), 3)
  wfp.25pct <- signif(as.numeric(quantile(wfp.data, 0.25)), 3)
  wfp.iqr <- signif(wfp.75pct - wfp.25pct, 3)
  wfp.tabler <- paste0(wfp.iqr, ' [', wfp.25pct, ', ', wfp.75pct, ']')
  
  tmp.tab <- matrix(c(aop.tabler, cch.tabler, cci.tabler, ccn.tabler, cfr.tabler, cir.tabler, cmo.tabler, cnr.tabler,
                      ctg.tabler, dbl.tabler, fnp.tabler, for.tabler, fsp.tabler, gom.tabler, gwm.tabler, hfr.tabler,
                      lhy.tabler, mch.tabler, mci.tabler, mcn.tabler, mir.tabler, mnr.tabler, mtg.tabler, nch.tabler,
                      nci.tabler, nir.tabler, nnr.tabler, ntg.tabler, oac.tabler, ohy.tabler, osp.tabler, pas.tabler, 
                      sch.tabler, scl.tabler, sgg.tabler, sho.tabler, som.tabler, soy.tabler, stb.tabler, stf.tabler, 
                      swm.tabler, wfp.tabler, wto.tabler), nrow = 43, ncol = 1)
  colnames(tmp.tab) = c('IQR of Unit Flows (cfs/sq. mi) [25th, 75th]')
  rownames(tmp.tab) = c('aop', 'cch', 'cci', 'ccn', 'cfr', 'cir', 'cmo', 'cnr',
                        'ctg', 'dbl', 'fnp', 'for', 'fsp', 'gom', 'gwm', 'hfr',
                        'lhy', 'mch', 'mci', 'mcn', 'mir', 'mnr', 'mtg', 'nch',
                        'nci', 'nir', 'nnr', 'ntg', 'oac', 'ohy', 'osp', 'pas',
                        'sch', 'scl', 'sgg', 'sho', 'som', 'soy', 'stb', 'stf',
                        'swm', 'wfp', 'wto')
  
  tmp.tab <- kable(format(tmp.tab, digits = 3, drop0trailing = TRUE))
  return(tmp.tab)
}
